# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-25 22:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojoSecrets', '0003_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('secret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='dojoSecrets.Secret')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='dojoSecrets.User')),
            ],
        ),
    ]
