# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-25 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojoSecrets', '0004_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
